---
deployment:
  tasks:
    - /bin/cp grip-api.php /home/addc5vqc95ni/public_html/grip/grip-api.php
    - /bin/cp grip-version.php /home/addc5vqc95ni/public_html/grip/grip-version.php
    - /bin/cp schema.sql /home/addc5vqc95ni/public_html/grip/schema.sql
    - /bin/rm -f /home/addc5vqc95ni/public_html/grip/grip-index.html
